- name: This playbook will demonstrate how to perform installation
  hosts: all
  become: yes
  vars:
    - proxy_conf:
        http_proxy: http://10.19.16.165:8080
        https_proxy: https://10.19.16.165:8080
  tasks:
    - name: Install tree utility
      apt: name=tree update_cache=yes state=present
      environment: "{{proxy_conf}}"
